Had to switch fully over to the new module names as there was a weird edge case bug caused by using both Sire.Mol and sire.legacy.Mol.
Have some small edge cases to deal with now

FAILED test/Process/test_somd.py::test_pert_file[test/input/morphs/morph01.pickle-test/input/morphs/morph01.pert] -
ModuleNotFoundErr...
FAILED test/Process/test_somd.py::test_pert_res_num - ModuleNotFoundError: No module named 'Sire'
FAILED
test/Sandpit/Exscientia/Process/test_somd.py::test_pert_file[test/Sandpit/Exscientia/input/morphs/morph01.pickle-test/Sandpit/Exscientia/input/morphs/morph01.pert]
FAILED test/Sandpit/Exscientia/Process/test_somd.py::test_pert_res_num - ModuleNotFoundError: No module named 'Sire'
FAILED test/Sandpit/Exscientia/_SireWrappers/test_molecule.py::test_makeCompatibleWith - ValueError: 'Invalid search query:
'element F'
FAILED test/_SireWrappers/test_molecule.py::test_makeCompatibleWith - ValueError: 'Invalid search query: 'element F'

The test_somd failures are because we now can't unpickle a file that expects to load Sire instead of sire

The 'element F' failure is unexpected and will be debugged later